### ISSUE TITLE
Automate publishing of blog posts to twitter, linked in, and medium

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/blog#30]
Looks like the way to go for this is via IFTTT

https://ictsolved.github.io/auto-post-articles-from-jekyll-blog-to-social-sites/
https://www.jflh.ca/2017-02-08-how-i-automate-social-media-sharing-of-my-jekyll-blog-articles
https://github.com/eduardoboucas/jekyll-social

**Comment by abarisuzuner** [comment]
Twitter and LinkedIn is automated. For medium we need a separate feed. It will be handled in a new issue.
